# This file was generated by GoReleaser. DO NOT EDIT.
cask "coderank" do
  version "0.1.3"

  on_macos do
    on_intel do
      url "https://github.com/coderank-dev/coderank/releases/download/v#{version}/coderank_#{version}_darwin_amd64.tar.gz"
      sha256 "d9212325e4ab9442479cbb6fc18e098566bd9e959f518b77b1bbb94bb416689f"
    end
    on_arm do
      url "https://github.com/coderank-dev/coderank/releases/download/v#{version}/coderank_#{version}_darwin_arm64.tar.gz"
      sha256 "8150d81ee86241e1eee7406dae190767402e3adb07160b2ceaee17285bf3ddd4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/coderank-dev/coderank/releases/download/v#{version}/coderank_#{version}_linux_amd64.tar.gz"
      sha256 "35051e4501526a84c9ccab83a4787422f88aac66a73f4b04b011c65502935aff"
    end
    on_arm do
      url "https://github.com/coderank-dev/coderank/releases/download/v#{version}/coderank_#{version}_linux_arm64.tar.gz"
      sha256 "8901f7e4a482bb5ebb134ebab8ef9929d1519cf7797f372bfc1f2643cf1c21fd"
    end
  end

  name "coderank"
  desc "AI-optimized library documentation for coding agents"
  homepage "https://coderank.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "coderank"

  # No zap stanza required

end
