# This file was generated by GoReleaser. DO NOT EDIT.
cask "coderank" do
  version "0.1.5"

  on_macos do
    on_intel do
      url "https://github.com/coderank-dev/coderank/releases/download/v#{version}/coderank_#{version}_darwin_amd64.tar.gz"
      sha256 "15d78e1e5f2b1953197a94c120131a83ea35ae4a4cf6895e831a1e0e13b042fa"
    end
    on_arm do
      url "https://github.com/coderank-dev/coderank/releases/download/v#{version}/coderank_#{version}_darwin_arm64.tar.gz"
      sha256 "cff5e6f62dffa978e29c38f5a642dc2ad4f79c645144c5c9fcf3fed2674e82da"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/coderank-dev/coderank/releases/download/v#{version}/coderank_#{version}_linux_amd64.tar.gz"
      sha256 "f1ceb80cf3b3e5ab21f8557b9718baafc1239f045f2de904e9c6392d00f1993d"
    end
    on_arm do
      url "https://github.com/coderank-dev/coderank/releases/download/v#{version}/coderank_#{version}_linux_arm64.tar.gz"
      sha256 "8466da80ee79c34664635a0ab8bf0dbd03afb4c386ef1585f6358545b46ceb2c"
    end
  end

  name "coderank"
  desc "AI-optimized library documentation for coding agents"
  homepage "https://coderank.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "coderank"

  # No zap stanza required

end
