# This file was generated by GoReleaser. DO NOT EDIT.
cask "coderank" do
  version "0.1.4"

  on_macos do
    on_intel do
      url "https://github.com/coderank-dev/coderank/releases/download/v#{version}/coderank_#{version}_darwin_amd64.tar.gz"
      sha256 "2325874e7c4adcdff8c2bbcc7382c52da4ce437a0b01a6e68825f3dae5abfc24"
    end
    on_arm do
      url "https://github.com/coderank-dev/coderank/releases/download/v#{version}/coderank_#{version}_darwin_arm64.tar.gz"
      sha256 "660fe87e52801fef73ec80892bcf39d48283521f16750c3d8d87e4fa3c1a0413"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/coderank-dev/coderank/releases/download/v#{version}/coderank_#{version}_linux_amd64.tar.gz"
      sha256 "e5b94dd5400fe6894e8475e9c7fbd003efb761938f508514bdbda3f35bf99ac4"
    end
    on_arm do
      url "https://github.com/coderank-dev/coderank/releases/download/v#{version}/coderank_#{version}_linux_arm64.tar.gz"
      sha256 "23d5aa6b08ed9640410de21af45099ec40d4eeca4a65edb150723395198e1328"
    end
  end

  name "coderank"
  desc "AI-optimized library documentation for coding agents"
  homepage "https://coderank.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "coderank"

  # No zap stanza required

end
